[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=MMT -e 'Custom branding name for YouTube' -OappName=YouTube -e 'Custom header for YouTube' -OcustomHeader=Premium"

